# Generated by Django 4.2.6 on 2023-11-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_yourmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='yourmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
