# Generated by Django 4.2.6 on 2023-11-16 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_yourmodel_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yourmodel',
            old_name='image',
            new_name='images',
        ),
    ]
