# Generated by Django 4.2.6 on 2023-11-17 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
