# Generated by Django 4.2.6 on 2023-11-17 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.customuser')),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp_secret_key',
        ),
    ]
